version: '3.8'

services:
  db:
    image: postgres:17
    container_name: plnx_mobapp_db
    environment:
      POSTGRES_DB: plnxmobapp_db
      POSTGRES_USER: plnxmobapp_user
      POSTGRES_PASSWORD: plnxmobapp_pwd
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: plnx_django_backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DB_NAME=plnxmobapp_db
      - DB_USER=plnxmobapp_user
      - DB_PASSWORD=plnxmobapp_pwd
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db

volumes:
  postgres_data: